// Analytics.jsx - COMPLETE FIXED VERSION
import { useState } from 'react'
import { O } from './adminUtils'
import { BarChart3, TrendingUp, Users, DollarSign, Calendar, Download, Eye, Activity } from 'lucide-react'

export default function Analytics() {
  const [dateRange, setDateRange] = useState('month')
  const stats = { totalRevenue: 456789, totalUsers: 125430, activeUsers: 34210, conversionRate: 27.3, averageOrderValue: 156, retentionRate: 68.5 }
  const weeklyData = [{ day: 'Mon', users: 1250, revenue: 12500 }, { day: 'Tue', users: 1420, revenue: 14800 }, { day: 'Wed', users: 1380, revenue: 13500 }, { day: 'Thu', users: 1560, revenue: 16200 }, { day: 'Fri', users: 1890, revenue: 19500 }, { day: 'Sat', users: 2100, revenue: 22500 }, { day: 'Sun', users: 1780, revenue: 18200 }]
  const topPerformers = [{ name: 'CryptoKing', xp: 245000, referrals: 89, earnings: 3450 }, { name: 'WhaleX', xp: 198000, referrals: 67, earnings: 2780 }, { name: 'Phoenix', xp: 167000, referrals: 54, earnings: 2340 }, { name: 'FemTech', xp: 145000, referrals: 43, earnings: 1980 }, { name: 'Rita', xp: 123000, referrals: 38, earnings: 1670 }]

  return (
    <div>
      <div style={{ marginBottom: 20 }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 10 }}><div><h1 style={{ fontSize: 22, fontWeight: 800, color: '#001F54', margin: 0 }}>Analytics Dashboard</h1><p style={{ fontSize: 12, color: '#8899AA', marginTop: 4 }}>Platform metrics and insights</p></div><div style={{ display: 'flex', gap: 8 }}><select value={dateRange} onChange={e => setDateRange(e.target.value)} style={{ padding: '6px 14px', borderRadius: 30, border: '1px solid #E9EDF2', fontSize: 11, background: '#fff' }}><option value="week">Last 7 days</option><option value="month">Last 30 days</option><option value="quarter">Last 90 days</option></select><button style={{ padding: '6px 14px', borderRadius: 30, border: '1px solid #E9EDF2', background: '#fff', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 4, fontSize: 11 }}><Download size={12} /> Export</button></div></div></div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(170px, 1fr))', gap: 12, marginBottom: 20 }}>
        <div style={{ background: '#fff', borderRadius: 16, padding: 12, border: '1px solid #E9EDF2' }}><div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}><div style={{ width: 32, height: 32, borderRadius: 10, background: '#10B98112', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><DollarSign size={16} color="#10B981" /></div><span style={{ fontSize: 10, color: '#8899AA' }}>Total Revenue</span></div><div style={{ fontSize: 20, fontWeight: 800, color: '#001F54' }}>${stats.totalRevenue.toLocaleString()}</div><div style={{ fontSize: 10, color: '#10B981', marginTop: 2 }}>↑ +12.5%</div></div>
        <div style={{ background: '#fff', borderRadius: 16, padding: 12, border: '1px solid #E9EDF2' }}><div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}><div style={{ width: 32, height: 32, borderRadius: 10, background: '#6366F112', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><Users size={16} color="#6366F1" /></div><span style={{ fontSize: 10, color: '#8899AA' }}>Total Users</span></div><div style={{ fontSize: 20, fontWeight: 800, color: '#001F54' }}>{stats.totalUsers.toLocaleString()}</div><div style={{ fontSize: 10, color: '#10B981', marginTop: 2 }}>↑ +8.2%</div></div>
        <div style={{ background: '#fff', borderRadius: 16, padding: 12, border: '1px solid #E9EDF2' }}><div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}><div style={{ width: 32, height: 32, borderRadius: 10, background: '#F59E0B12', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><Activity size={16} color="#F59E0B" /></div><span style={{ fontSize: 10, color: '#8899AA' }}>Active Users</span></div><div style={{ fontSize: 20, fontWeight: 800, color: '#001F54' }}>{stats.activeUsers.toLocaleString()}</div><div style={{ fontSize: 10, color: '#F59E0B', marginTop: 2 }}>{((stats.activeUsers / stats.totalUsers) * 100).toFixed(0)}% of total</div></div>
        <div style={{ background: '#fff', borderRadius: 16, padding: 12, border: '1px solid #E9EDF2' }}><div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}><div style={{ width: 32, height: 32, borderRadius: 10, background: '#8B5CF612', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><TrendingUp size={16} color="#8B5CF6" /></div><span style={{ fontSize: 10, color: '#8899AA' }}>Conversion Rate</span></div><div style={{ fontSize: 20, fontWeight: 800, color: '#001F54' }}>{stats.conversionRate}%</div><div style={{ fontSize: 10, color: '#10B981', marginTop: 2 }}>↑ +2.1%</div></div>
      </div>
      <div style={{ background: '#fff', borderRadius: 20, padding: 16, border: '1px solid #E9EDF2', marginBottom: 20 }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14, flexWrap: 'wrap', gap: 8 }}><div style={{ display: 'flex', alignItems: 'center', gap: 6 }}><BarChart3 size={16} color={O} /><span style={{ fontWeight: 600, fontSize: 13 }}>Daily Activity</span></div><div style={{ display: 'flex', gap: 6 }}><button style={{ padding: '3px 10px', borderRadius: 20, border: '1px solid #E9EDF2', background: '#F7F8FC', fontSize: 10, cursor: 'pointer' }}>Users</button><button style={{ padding: '3px 10px', borderRadius: 20, border: `1px solid ${O}`, background: `${O}10`, color: O, fontSize: 10, cursor: 'pointer' }}>Revenue</button></div></div>
        <div style={{ display: 'flex', alignItems: 'flex-end', gap: 8, height: 150 }}>{weeklyData.map(day => { const maxRevenue = Math.max(...weeklyData.map(d => d.revenue)); const height = (day.revenue / maxRevenue) * 110; return (<div key={day.day} style={{ flex: 1, textAlign: 'center' }}><div style={{ height: height, background: O, borderRadius: 6, marginBottom: 6, width: '100%' }} /><div style={{ fontSize: 9, color: '#8899AA' }}>{day.day}</div><div style={{ fontSize: 8, fontWeight: 600, color: '#001F54' }}>${(day.revenue / 1000).toFixed(0)}k</div></div>) })}</div>
      </div>
      <div style={{ background: '#fff', borderRadius: 20, padding: 16, border: '1px solid #E9EDF2' }}><div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 12 }}><Eye size={16} color={O} /><span style={{ fontWeight: 600, fontSize: 13 }}>Top Performers</span></div><div style={{ overflowX: 'auto' }}><table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11 }}><thead><tr style={{ borderBottom: '1px solid #E9EDF2' }}><th style={{ padding: '8px 6px', textAlign: 'left', color: '#8899AA' }}>Rank</th><th style={{ padding: '8px 6px', textAlign: 'left', color: '#8899AA' }}>User</th><th style={{ padding: '8px 6px', textAlign: 'right', color: '#8899AA' }}>XP</th><th style={{ padding: '8px 6px', textAlign: 'right', color: '#8899AA' }}>Referrals</th><th style={{ padding: '8px 6px', textAlign: 'right', color: '#8899AA' }}>Earnings</th></tr></thead><tbody>{topPerformers.map((user, idx) => (<tr key={idx} style={{ borderBottom: '1px solid #E9EDF2' }}><td style={{ padding: '8px 6px', fontWeight: 700, color: O }}>#{idx + 1}</td><td style={{ padding: '8px 6px', fontWeight: 600, color: '#001F54' }}>{user.name}</td><td style={{ padding: '8px 6px', textAlign: 'right', color: '#5A6E8A' }}>{user.xp.toLocaleString()}</td><td style={{ padding: '8px 6px', textAlign: 'right', color: '#5A6E8A' }}>{user.referrals}</td><td style={{ padding: '8px 6px', textAlign: 'right', fontWeight: 700, color: '#10B981' }}>${user.earnings.toLocaleString()}</td></tr>))}</tbody></table></div></div>
    </div>
  )
}