// Referral.jsx - COMPLETE FIXED VERSION
import { useState } from 'react'
import { O } from './adminUtils'
import { Users, Gift, TrendingUp, DollarSign, Award, Settings, Save, Copy, Check, Share2, UserPlus } from 'lucide-react'

export default function Referral() {
  const [referralSettings, setReferralSettings] = useState({ bonusAmount: 10, bonusType: 'cash', referralLimit: 100, expiryDays: 30, levels: [{ level: 1, commission: 10, label: 'Direct Referral' }, { level: 2, commission: 5, label: 'Second Level' }, { level: 3, commission: 2, label: 'Third Level' }], minimumWithdrawal: 50, autoApprove: true, welcomeBonus: 5 })
  const [referralStats] = useState({ totalReferrals: 12450, activeReferrers: 3420, totalCommissions: 45600, monthlyCommissions: 8900, topReferrer: { name: "CryptoKing", count: 342, earnings: 1250 } })
  const [copied, setCopied] = useState(false)

  const updateCommission = (level, value) => setReferralSettings(prev => ({ ...prev, levels: prev.levels.map(l => l.level === level ? { ...l, commission: parseInt(value) || 0 } : l) }))
  const copyReferralLink = () => { navigator.clipboard.writeText('https://bigtenx.com/ref/admin'); setCopied(true); setTimeout(() => setCopied(false), 2000) }

  return (
    <div>
      <div style={{ marginBottom: 20 }}><h1 style={{ fontSize: 22, fontWeight: 800, color: '#001F54', margin: 0 }}>Referral System</h1><p style={{ fontSize: 12, color: '#8899AA', marginTop: 4 }}>Manage referral bonuses, commissions, and tracking</p></div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 12, marginBottom: 20 }}>
        <div style={{ background: '#fff', borderRadius: 16, padding: 12, border: '1px solid #E9EDF2' }}><div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}><div style={{ width: 32, height: 32, borderRadius: 10, background: `${O}12`, display: 'flex', alignItems: 'center', justifyContent: 'center' }}><Users size={16} color={O} /></div><span style={{ fontSize: 10, color: '#8899AA' }}>Total Referrals</span></div><div style={{ fontSize: 20, fontWeight: 800, color: '#001F54' }}>{referralStats.totalReferrals.toLocaleString()}</div></div>
        <div style={{ background: '#fff', borderRadius: 16, padding: 12, border: '1px solid #E9EDF2' }}><div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}><div style={{ width: 32, height: 32, borderRadius: 10, background: '#10B98112', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><UserPlus size={16} color="#10B981" /></div><span style={{ fontSize: 10, color: '#8899AA' }}>Active Referrers</span></div><div style={{ fontSize: 20, fontWeight: 800, color: '#001F54' }}>{referralStats.activeReferrers.toLocaleString()}</div></div>
        <div style={{ background: '#fff', borderRadius: 16, padding: 12, border: '1px solid #E9EDF2' }}><div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}><div style={{ width: 32, height: 32, borderRadius: 10, background: '#F59E0B12', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><DollarSign size={16} color="#F59E0B" /></div><span style={{ fontSize: 10, color: '#8899AA' }}>Total Commissions</span></div><div style={{ fontSize: 20, fontWeight: 800, color: '#001F54' }}>${referralStats.totalCommissions.toLocaleString()}</div></div>
        <div style={{ background: '#fff', borderRadius: 16, padding: 12, border: '1px solid #E9EDF2' }}><div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}><div style={{ width: 32, height: 32, borderRadius: 10, background: '#8B5CF612', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><TrendingUp size={16} color="#8B5CF6" /></div><span style={{ fontSize: 10, color: '#8899AA' }}>This Month</span></div><div style={{ fontSize: 20, fontWeight: 800, color: '#001F54' }}>${referralStats.monthlyCommissions.toLocaleString()}</div></div>
      </div>
      <div style={{ background: 'linear-gradient(135deg, #001F54, #003B8E)', borderRadius: 18, padding: 14, marginBottom: 20 }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 8 }}><div><div style={{ fontSize: 10, color: 'rgba(255,255,255,0.5)', marginBottom: 2 }}>🏆 Top Referrer</div><div style={{ fontSize: 16, fontWeight: 800, color: '#fff' }}>{referralStats.topReferrer.name}</div><div style={{ display: 'flex', gap: 12, marginTop: 4 }}><span style={{ fontSize: 11, color: O }}>{referralStats.topReferrer.count} referrals</span><span style={{ fontSize: 11, color: '#10B981' }}>${referralStats.topReferrer.earnings} earned</span></div></div><div style={{ background: 'rgba(255,255,255,0.1)', borderRadius: 30, padding: '6px 12px' }}><span style={{ fontSize: 11, color: O, fontWeight: 600 }}>⭐ VIP Member</span></div></div></div>
      <div style={{ background: '#fff', borderRadius: 20, padding: 16, border: '1px solid #E9EDF2', marginBottom: 16 }}><div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14 }}><Settings size={16} color={O} /><span style={{ fontWeight: 600, fontSize: 14 }}>Referral Settings</span></div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: 12, marginBottom: 16 }}><div><label style={{ fontSize: 10, fontWeight: 600, color: '#8899AA', marginBottom: 4, display: 'block' }}>Bonus Amount</label><div style={{ display: 'flex', gap: 6 }}><input type="number" value={referralSettings.bonusAmount} onChange={e => setReferralSettings({ ...referralSettings, bonusAmount: parseInt(e.target.value) || 0 })} style={{ flex: 1, padding: '8px', borderRadius: 10, border: '1px solid #E9EDF2', fontSize: 12 }} /><select value={referralSettings.bonusType} onChange={e => setReferralSettings({ ...referralSettings, bonusType: e.target.value })} style={{ width: 60, padding: '8px', borderRadius: 10, border: '1px solid #E9EDF2', fontSize: 12, background: '#F7F8FC' }}><option value="cash">$</option><option value="xp">XP</option></select></div></div>
          <div><label style={{ fontSize: 10, fontWeight: 600, color: '#8899AA', marginBottom: 4, display: 'block' }}>Referral Limit</label><input type="number" value={referralSettings.referralLimit} onChange={e => setReferralSettings({ ...referralSettings, referralLimit: parseInt(e.target.value) || 0 })} style={{ width: '100%', padding: '8px', borderRadius: 10, border: '1px solid #E9EDF2', fontSize: 12 }} /></div>
          <div><label style={{ fontSize: 10, fontWeight: 600, color: '#8899AA', marginBottom: 4, display: 'block' }}>Expiry Days</label><input type="number" value={referralSettings.expiryDays} onChange={e => setReferralSettings({ ...referralSettings, expiryDays: parseInt(e.target.value) || 0 })} style={{ width: '100%', padding: '8px', borderRadius: 10, border: '1px solid #E9EDF2', fontSize: 12 }} /></div>
          <div><label style={{ fontSize: 10, fontWeight: 600, color: '#8899AA', marginBottom: 4, display: 'block' }}>Welcome Bonus</label><input type="number" value={referralSettings.welcomeBonus} onChange={e => setReferralSettings({ ...referralSettings, welcomeBonus: parseInt(e.target.value) || 0 })} style={{ width: '100%', padding: '8px', borderRadius: 10, border: '1px solid #E9EDF2', fontSize: 12 }} /></div></div>
        <div style={{ marginBottom: 16 }}><div style={{ fontSize: 12, fontWeight: 600, color: '#001F54', marginBottom: 8 }}>Commission Structure</div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8 }}>{referralSettings.levels.map(level => (<div key={level.level} style={{ background: '#F7F8FC', borderRadius: 12, padding: 8, textAlign: 'center' }}><div style={{ fontSize: 10, color: '#8899AA' }}>Level {level.level}</div><div style={{ fontSize: 12, fontWeight: 600, color: '#001F54' }}>{level.label}</div><div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 4, marginTop: 6 }}><input type="number" value={level.commission} onChange={e => updateCommission(level.level, e.target.value)} style={{ width: 60, padding: '4px', borderRadius: 8, border: '1px solid #E9EDF2', textAlign: 'center', fontSize: 11 }} /><span style={{ fontSize: 11, color: O }}>%</span></div></div>))}</div></div>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '10px 0', borderTop: '1px solid #E9EDF2' }}><div><span style={{ fontSize: 12, fontWeight: 600, color: '#001F54' }}>Auto Approve Referrals</span><p style={{ fontSize: 9, color: '#8899AA', marginTop: 1 }}>Automatically approve qualified referrals</p></div><button onClick={() => setReferralSettings({ ...referralSettings, autoApprove: !referralSettings.autoApprove })} style={{ width: 40, height: 22, borderRadius: 11, background: referralSettings.autoApprove ? O : '#C0CCDA', border: 'none', cursor: 'pointer', position: 'relative' }}><span style={{ position: 'absolute', width: 18, height: 18, borderRadius: '50%', background: '#fff', top: 2, left: referralSettings.autoApprove ? 20 : 2, transition: 'left .2s' }} /></button></div>
        <button onClick={() => alert('Referral settings saved!')} style={{ width: '100%', background: O, border: 'none', padding: '10px', borderRadius: 30, color: '#fff', fontWeight: 600, marginTop: 12, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6 }}><Save size={14} /> Save Settings</button>
      </div>
      <div style={{ background: '#fff', borderRadius: 20, padding: 16, border: '1px solid #E9EDF2' }}><div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }}><Share2 size={16} color={O} /><span style={{ fontWeight: 600, fontSize: 13 }}>Master Referral Link</span></div><div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}><code style={{ flex: 1, padding: '10px', background: '#F7F8FC', borderRadius: 10, fontSize: 11, color: '#001F54', wordBreak: 'break-all' }}>https://bigtenx.com/ref/admin</code><button onClick={copyReferralLink} style={{ background: O, border: 'none', padding: '8px 16px', borderRadius: 30, color: '#fff', fontWeight: 600, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6 }}>{copied ? <Check size={12} /> : <Copy size={12} />}{copied ? 'Copied!' : 'Copy'}</button></div></div>
    </div>
  )
}