// XPLevels.jsx - FIXED (no duplicate background)
import { useState } from 'react'
import { O } from './adminUtils'
import { ChevronDown, ChevronUp, TrendingUp, Check, Award, Crown, Star, Gem, Zap } from 'lucide-react'

export default function XPLevels() {
  const [xpOpen, setXpOpen] = useState(false)
  const [dailyLoginXP, setDailyLoginXP] = useState(1)
  const [currentLevel, setCurrentLevel] = useState('bronze')
  const [levelSettings, setLevelSettings] = useState({
    bronze: { price: '$0', vaultUnit: '20 units', referralBonus: '5%', multiplier: '1x', benefits: ['Bronze badge', '20% commission'] },
    silver: { price: '$50', vaultUnit: '50 units', referralBonus: '10%', multiplier: '1.2x', benefits: ['Silver badge', '25% commission'] },
    gold: { price: '$150', vaultUnit: '100 units', referralBonus: '15%', multiplier: '1.5x', benefits: ['Gold badge', '30% commission', 'Priority support'] },
    diamond: { price: '$500', vaultUnit: '200 units', referralBonus: '20%', multiplier: '2x', benefits: ['Diamond badge', '35% commission', 'VIP support'] }
  })
  const [vipSettings, setVipSettings] = useState({ price: '$10', duration: '30 days', referralBonus: '$1', xpSpeed: '20%', benefits: ['20% XP Speed'] })
  const [newBenefit, setNewBenefit] = useState('')
  const [newVipBenefit, setNewVipBenefit] = useState('')
  const [xpFeatures, setXpFeatures] = useState({ levelMultiplier: false, task: true, market: false, store: false })

  const levels = [{ id: 'bronze', name: 'Bronze', icon: '🥉', color: '#CD7F32' }, { id: 'silver', name: 'Silver', icon: '🥈', color: '#909090' }, { id: 'gold', name: 'Gold', icon: '🥇', color: '#D4A000' }, { id: 'diamond', name: 'Diamond', icon: '💎', color: '#38B6FF' }, { id: 'vip', name: 'VIP', icon: '👑', color: '#8B5CF6' }]

  const toggleFeature = (key) => setXpFeatures(prev => ({ ...prev, [key]: !prev[key] }))
  const addBenefit = () => { if (newBenefit.trim()) { setLevelSettings(prev => ({ ...prev, [currentLevel]: { ...prev[currentLevel], benefits: [...prev[currentLevel].benefits, newBenefit.trim()] } })); setNewBenefit('') } }
  const removeBenefit = (benefitToRemove) => setLevelSettings(prev => ({ ...prev, [currentLevel]: { ...prev[currentLevel], benefits: prev[currentLevel].benefits.filter(b => b !== benefitToRemove) } }))
  const addVipBenefit = () => { if (newVipBenefit.trim()) { setVipSettings(prev => ({ ...prev, benefits: [...prev.benefits, newVipBenefit.trim()] })); setNewVipBenefit('') } }
  const removeVipBenefit = (benefitToRemove) => setVipSettings(prev => ({ ...prev, benefits: prev.benefits.filter(b => b !== benefitToRemove) }))
  const updateLevelSetting = (key, value) => setLevelSettings(prev => ({ ...prev, [currentLevel]: { ...prev[currentLevel], [key]: value } }))
  const updateVipSetting = (key, value) => setVipSettings(prev => ({ ...prev, [key]: value }))
  const saveSettings = () => alert(currentLevel === 'vip' ? 'VIP settings saved!' : `${currentLevel.charAt(0).toUpperCase() + currentLevel.slice(1)} settings saved!`)

  return (
    <div>
      <div style={{ marginBottom: 20 }}><h1 style={{ fontSize: 22, fontWeight: 800, color: '#001F54', margin: 0 }}>XP & Levels</h1><p style={{ fontSize: 12, color: '#8899AA', marginTop: 4 }}>Configure XP rewards, level benefits, and VIP perks</p></div>
      <div style={{ background: '#fff', borderRadius: 20, marginBottom: 16, overflow: 'hidden', border: '1px solid #E9EDF2' }}>
        <div onClick={() => setXpOpen(!xpOpen)} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px 16px', cursor: 'pointer', background: '#fff' }}><div style={{ display: 'flex', alignItems: 'center', gap: 10 }}><Zap size={16} color={O} /><span style={{ fontSize: 14, fontWeight: 700, color: '#001F54' }}>XP Configuration</span></div>{xpOpen ? <ChevronUp size={14} color="#8899AA" /> : <ChevronDown size={14} color="#8899AA" />}</div>
        {xpOpen && (<div style={{ padding: '0 16px 16px 16px', borderTop: '1px solid #E9EDF2' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '12px 0', borderBottom: '1px solid #E9EDF2' }}><span style={{ fontSize: 12, fontWeight: 600, color: '#001F54' }}>Daily login</span><div style={{ display: 'flex', gap: 10 }}><input type="number" value={dailyLoginXP} onChange={e => setDailyLoginXP(parseInt(e.target.value) || 0)} style={{ width: 60, padding: '6px 8px', borderRadius: 10, border: '1px solid #E9EDF2', textAlign: 'center', background: '#F7F8FC', fontSize: 12 }} /><button onClick={() => alert(`Daily login XP set to ${dailyLoginXP} XP`)} style={{ background: O, border: 'none', padding: '6px 14px', borderRadius: 20, color: '#fff', fontWeight: 600, fontSize: 10, cursor: 'pointer' }}>Save</button></div></div>
          {[{ key: 'levelMultiplier', icon: TrendingUp, label: 'Level multiplier' }, { key: 'task', icon: Zap, label: 'Task' }, { key: 'market', icon: () => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke={O} strokeWidth="2"><path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"/><line x1="3" y1="6" x2="21" y2="6"/><path d="M16 10a4 4 0 0 1-8 0"/></svg>, label: 'Market' }, { key: 'store', icon: () => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke={O} strokeWidth="2"><rect x="2" y="7" width="20" height="14" rx="2"/><path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"/></svg>, label: 'Store' }].map(feat => (<div key={feat.key} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '12px 0', borderBottom: '1px solid #E9EDF2' }}><div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>{typeof feat.icon === 'function' ? feat.icon() : <feat.icon size={14} color={O} />}<span style={{ fontSize: 12, fontWeight: 500, color: '#001F54' }}>{feat.label}</span></div><div onClick={() => toggleFeature(feat.key)} style={{ width: 18, height: 18, borderRadius: 5, border: `2px solid ${xpFeatures[feat.key] ? O : '#C0CCDA'}`, background: xpFeatures[feat.key] ? O : 'white', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>{xpFeatures[feat.key] && <Check size={10} color="#fff" />}</div></div>))}
        </div>)}
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8, marginBottom: 16 }}>{levels.map(level => (<div key={level.id} onClick={() => setCurrentLevel(level.id)} style={{ background: currentLevel === level.id ? '#FFF8F0' : '#fff', borderRadius: 16, padding: '10px 4px', textAlign: 'center', cursor: 'pointer', border: currentLevel === level.id ? `1.5px solid ${O}` : '1.5px solid transparent' }}><div style={{ fontSize: 24, marginBottom: 4 }}>{level.icon}</div><div style={{ fontSize: 12, fontWeight: 700, color: '#001F54' }}>{level.name}</div></div>))}</div>
      {currentLevel !== 'vip' && (<div style={{ background: '#fff', borderRadius: 20, padding: 16, border: '1px solid #E9EDF2' }}><div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14, paddingBottom: 8, borderBottom: `2px solid ${O}` }}>{currentLevel === 'bronze' && <Crown size={16} color={O} />}{currentLevel === 'silver' && <Award size={16} color={O} />}{currentLevel === 'gold' && <Star size={16} color={O} />}{currentLevel === 'diamond' && <Gem size={16} color={O} />}<h3 style={{ fontSize: 15, fontWeight: 800, color: '#001F54' }}>{currentLevel.charAt(0).toUpperCase() + currentLevel.slice(1)} Settings</h3></div>
        <div style={{ marginBottom: 12 }}><div style={{ fontSize: 11, fontWeight: 600, color: '#001F54', marginBottom: 6 }}>Price</div><input type="text" value={levelSettings[currentLevel]?.price} onChange={e => updateLevelSetting('price', e.target.value)} style={{ width: '100%', padding: '10px', borderRadius: 12, border: '1px solid #E9EDF2', background: '#F7F8FC', fontSize: 12 }} /></div>
        <div style={{ marginBottom: 12 }}><div style={{ fontSize: 11, fontWeight: 600, color: '#001F54', marginBottom: 6 }}>Vault Unit</div><input type="text" value={levelSettings[currentLevel]?.vaultUnit} onChange={e => updateLevelSetting('vaultUnit', e.target.value)} style={{ width: '100%', padding: '10px', borderRadius: 12, border: '1px solid #E9EDF2', background: '#F7F8FC', fontSize: 12 }} /></div>
        <div style={{ marginBottom: 12 }}><div style={{ fontSize: 11, fontWeight: 600, color: '#001F54', marginBottom: 6 }}>Referral Bonus</div><input type="text" value={levelSettings[currentLevel]?.referralBonus} onChange={e => updateLevelSetting('referralBonus', e.target.value)} style={{ width: '100%', padding: '10px', borderRadius: 12, border: '1px solid #E9EDF2', background: '#F7F8FC', fontSize: 12 }} /></div>
        <div style={{ marginBottom: 12 }}><div style={{ fontSize: 11, fontWeight: 600, color: '#001F54', marginBottom: 6 }}>Multiplier</div><input type="text" value={levelSettings[currentLevel]?.multiplier} onChange={e => updateLevelSetting('multiplier', e.target.value)} style={{ width: '100%', padding: '10px', borderRadius: 12, border: '1px solid #E9EDF2', background: '#F7F8FC', fontSize: 12 }} /></div>
        <div style={{ marginBottom: 12 }}><div style={{ fontSize: 11, fontWeight: 600, color: '#001F54', marginBottom: 6 }}>Benefits</div><div style={{ background: '#F7F8FC', borderRadius: 12, padding: 8 }}>{levelSettings[currentLevel]?.benefits.map((benefit, idx) => (<div key={idx} style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '6px 0', borderBottom: idx < levelSettings[currentLevel].benefits.length - 1 ? '1px solid #E9EDF2' : 'none' }}><Check size={10} color={O} /><span style={{ fontSize: 11, color: '#001F54' }}>{benefit}</span><button onClick={() => removeBenefit(benefit)} style={{ marginLeft: 'auto', background: 'none', border: 'none', color: '#DC2626', cursor: 'pointer', fontSize: 10 }}>✕</button></div>))}</div><div style={{ display: 'flex', gap: 6, marginTop: 8 }}><input type="text" placeholder="Add benefit..." value={newBenefit} onChange={e => setNewBenefit(e.target.value)} style={{ flex: 1, padding: '8px', borderRadius: 12, border: '1px solid #E9EDF2', fontSize: 11 }} /><button onClick={addBenefit} style={{ background: O, border: 'none', width: 30, height: 30, borderRadius: 10, color: '#fff', cursor: 'pointer' }}>+</button></div></div>
        <button onClick={saveSettings} style={{ width: '100%', background: O, border: 'none', padding: '10px', borderRadius: 30, color: '#fff', fontWeight: 600, cursor: 'pointer' }}>Save Changes</button>
      </div>)}
      {currentLevel === 'vip' && (<div style={{ background: 'linear-gradient(135deg, #FFF8F0, #FFF2E6)', borderRadius: 20, padding: 16, border: '1px solid rgba(255,111,0,0.2)' }}><div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14, paddingBottom: 8, borderBottom: `2px solid ${O}` }}><Crown size={20} color={O} /><h3 style={{ fontSize: 17, fontWeight: 800, color: '#001F54' }}>VIP Settings</h3></div>
        {[{ key: 'price', label: 'VIP Price', value: vipSettings.price }, { key: 'duration', label: 'Duration', value: vipSettings.duration }, { key: 'referralBonus', label: 'Referral Bonus', value: vipSettings.referralBonus }, { key: 'xpSpeed', label: 'XP Speed', value: vipSettings.xpSpeed }].map(setting => (<div key={setting.key} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14, padding: '6px 0', borderBottom: '1px solid rgba(0,31,84,0.08)' }}><span style={{ fontSize: 13, fontWeight: 600, color: '#001F54' }}>{setting.label}</span><div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><input type="text" value={setting.value} onChange={e => updateVipSetting(setting.key, e.target.value)} style={{ width: 90, padding: '6px 10px', borderRadius: 12, border: '1px solid #E9EDF2', background: '#fff', fontSize: 12 }} /><button onClick={() => alert(`${setting.label} saved`)} style={{ background: O, border: 'none', padding: '6px 14px', borderRadius: 30, color: '#fff', fontWeight: 600, cursor: 'pointer', fontSize: 11 }}>Save</button></div></div>))}
        <div style={{ marginTop: 12, background: '#fff', borderRadius: 16, padding: 12 }}><div style={{ fontSize: 12, fontWeight: 700, color: '#001F54', marginBottom: 8 }}>Benefits</div>{vipSettings.benefits.map((benefit, idx) => (<div key={idx} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '6px 0', borderBottom: idx < vipSettings.benefits.length - 1 ? '1px solid #E9EDF2' : 'none' }}><Check size={10} color={O} /><span style={{ fontSize: 12, color: '#001F54' }}>{benefit}</span><button onClick={() => removeVipBenefit(benefit)} style={{ marginLeft: 'auto', background: 'none', border: 'none', color: '#DC2626', cursor: 'pointer' }}>✕</button></div>))}<div style={{ display: 'flex', gap: 8, marginTop: 8 }}><input type="text" placeholder="Add benefit..." value={newVipBenefit} onChange={e => setNewVipBenefit(e.target.value)} style={{ flex: 1, padding: '8px', borderRadius: 12, border: '1px solid #E9EDF2', fontSize: 11 }} /><button onClick={addVipBenefit} style={{ background: O, border: 'none', width: 30, height: 30, borderRadius: 10, color: '#fff', cursor: 'pointer' }}>+</button></div></div>
      </div>)}
    </div>
  )
}